### ISSUE TITLE
[extension_discovery] Consider `extension/<package>/config.yaml` instead?

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/tools#152]
Should we use YAML instead of JSON, in `extension/<package>/config.yaml`, it's more consistent with other tooling.

A bit slower, but given how much we're able to leverage caching in `extension_discovery` using file modification timestamp, the overhead of parsing YAML might not be so bad. Since we'd never need to do it every time. Only when a `config.yaml` has been modified since the cache was created.

@kenzieschmoll, wdyt? I think we should do it now or never :D

**Comment by kenzieschmoll** [comment]
If we used a yaml file instead of json, could `package:extension_discovery` still return a Map object here: https://github.com/dart-lang/tools/blob/main/pkgs/extension_discovery/lib/extension_discovery.dart#L64? This would cause the least amount of churn and be ideal because DevTools server and DevTools app pass this information over json RPC, so we wouldn't want to introduce something that adds more serialization overhead.

If so, then switching to yaml for consistency sounds good.

**Comment by jonasfj** [comment]
We could return a map, by just requiring it, it would be orthogonal to the question of using YAML or not.

top-level YAML can be list, string, etc.

But, I see the point: if we want to make it more consistent with other tooling, then we should also force that it be a map.

**Comment by jonasfj** [comment]
If we want to do these breaking changes, I would suggest we also consider: https://github.com/dart-lang/tools/issues/139

**Comment by kenzieschmoll** [comment]
On the devtools server side, we also check that `config` is a Map here: https://github.com/flutter/devtools/blob/master/packages/devtools_shared/lib/src/extensions/extension_manager.dart#L78-L87. 

But I would like to avoid having to do Yaml parsing on the DevTools server. So ideal solution from my perspective is `package:extension_discovery` can parse the yaml and if it is a yaml map, include a `Map` in the `Extension.config` object field
