### ISSUE TITLE
update sdk repo for next roll

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/tools#164]
When rolling this into the sdk, we'll need to update the analyzer code base to account for the changes in https://github.com/dart-lang/tools/pull/161.

cc @eliasyishak

**Comment by eliasyishak** [comment]
I'm not sure where the updates for the changes made in #161 need to be made.  I know we will need to make updates for #163 because we have a new getter on an instance that is being implemented in [this file](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/test/src/analytics/analytics_manager_test.dart#L559-L564)

If I wanted to update the sdk repo, can I manually change the DEPS for this package and make the necessary changes in Gerrit?

**Comment by devoncarew** [comment]
Yup, that works. You'll see the necessary changes if you run `dart analyze` over `pkg/analysis_server`.

**Comment by eliasyishak** [comment]
Just merged https://dart-review.googlesource.com/c/sdk/+/326842 to update the sdk, should be good to close this out now?

**Comment by devoncarew** [comment]
Yup - thanks for the quick response.
