### ISSUE TITLE
Tests with `Isolate.run` pause indefinitely.

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/tools#520]
This never prints 42 when it's run using `--pause-isolates-on-exit`.

```
import 'dart:isolate';

void main() async {
  print(await Isolate.run(() => 42));
}
```

And since coverage uses the `--pause-isolates-on-exit` flag (presumably to communicate with the VM service), the tests with `Isolate.run` time out.

**Comment by liamappelbe** [comment]
Just getting to this now. To summarize, the current flow is we start the test, wait for all the isolates to be paused, then collect all the coverage, then resume all the isolates.

The proposed new flow is that we start the test, listen for individual isolate's `PauseExit` events, collect coverage for the paused isolate, then resume it. We keep going with this process until there are no isolates left. We also need to take care to handle the case where we miss some of the isolate pause events before the listener is set up.

Unfortunately that approach won't quite work in the presence of isolate groups. The coverage counters are shared between all the isolates in a group. In the currently flow we only collect coverage for one isolate in a group. If we naively apply that logic in the new flow, we'll undercount coverage by only collecting coverage for the entire group when its first isolate exits. If we instead omit this logic and collect coverage for all isolates, we'll overcount coverage (that's less problematic, but users have complained about it before).

So instead we need to collect coverage for an isolate group only when its final isolate exits. I'm not quite sure of the best way to do this. My goal is generally to minimize the number of RPCs. My current thinking is that when I get a pause event, I can query `vm.isolates`, which returns a list of isolate refs, which contain the isolate's group ID. If the paused isolate is the only isolate in that group, I can collect coverage. That's 1 RPC per pause event. @bkonyi Can you think of a cleaner solution?

**Comment by liamappelbe** [comment]
I've got a mostly working solution, except for one annoying issue. If you're gathering coverage on a test where the main isolate doesn't wait for its child isolates to finish, the main isolate can finish first. In that case the flow is:

1. Main isolate starts. Coverage tool sees it.
2. Main isolate spawns child. Coverage tool sees that there are 2 isolates in the group.
3. Main isolate doesn't await child, so it finishes, and enters pause-on-exit state
4. Coverage tool sees that the main isolate is not the last isolate in its group, so doesn't gather coverage. Instead it just resumes the main isolate, allowing it to exit.
5. Child isolate finishes, and enters pause-on-exit state
6. Coverage tool sees that it's the last isolate, so starts collecting coverage.
7. Once coverage is collected, the child isolate is resumed and exits.

The problem is I'm seeing the VM service being disposed early, some time around step 6 or 7 (eg `getSourceReport: (112) Service has disappeared`). I think what's happening is that the lifetime of the VM service is tied to the main isolate, and it's being shut down before the child isolate is collected and resumed.

Potential fixes:

1. I can fix this particular test by having the main isolate wait for the child isolate to exit. I've verified this works, but this is not a general solution. The tool needs to be robust to this case.
2. Change the VM service to stay alive until *all* isolates are closed. I don't know how feasible this is, and I'd rather not wait for Dart 3.7 to fix this bug.
3. Delay resuming the main isolate until all other isolates have been resumed. I've verified this works, and this is my preferred solution. The only issue is I'm not sure how to reliably detect the main isolate. My current (super hacky) solution is to check `isolateRef.name == "main"`. @bkonyi is there a better way of detecting which isolate is the main isolate?

**Comment by bkonyi** [comment]
> I think what's happening is that the lifetime of the VM service is tied to the main isolate, and it's being shut down before the child isolate is collected and resumed.

As soon as the main isolate exits, the VM starts shutting down which will kill all the isolates immediately (although the service isolate should be one of the last to shutdown).

> 2. Change the VM service to stay alive until _all_ isolates are closed. I don't know how feasible this is, and I'd rather not wait for Dart 3.7 to fix this bug.

[The VM service is only shutdown after all isolates are killed](https://github.com/dart-lang/sdk/blob/b3e1eec36f1551d00bca7caea883ff7ccc73c435/runtime/vm/dart.cc#L693).

> 3. Delay resuming the main isolate until all other isolates have been resumed. I've verified this works, and this is my preferred solution. The only issue is I'm not sure how to reliably detect the main isolate. My current (super hacky) solution is to check `isolateRef.name == "main"`. @bkonyi is there a better way of detecting which isolate is the main isolate?

Unfortunately the definition of the "main" isolate is embedder specific, so there's no generic way to query whether or not an isolate is the main isolate. For the standalone VM, checking for the isolate named "main" will work, but it's purely an implementation detail and could change in the future (at least in theory). The Flutter engine may assign a different name to the main isolate in Flutter apps as well.

@kenzieschmoll, does DevTools just assume the [first non-system isolate to start is the main isolate](https://github.com/flutter/devtools/blob/2b3bed912146c800ac7b8ec34a5ea4ae1bb6dcf6/packages/devtools_app_shared/lib/src/service/isolate_manager.dart#L171) or is there another check that's more consistent that's used elsewhere?

**Comment by liamappelbe** [comment]
> @kenzieschmoll, does DevTools just assume the [first non-system isolate to start is the main isolate](https://github.com/flutter/devtools/blob/2b3bed912146c800ac7b8ec34a5ea4ae1bb6dcf6/packages/devtools_app_shared/lib/src/service/isolate_manager.dart#L171) or is there another check that's more consistent that's used elsewhere?

Looking at that code link, they're catching the first `EventKind.kIsolateStart` event. But package:coverage usually doesn't subscribe to the event stream early enough to catch that.

Another approach I thought of was to assume the first isolate in `service.getVM().isolates` was the main isolate (under the assumption that no isolates have shut down yet and shuffled the order, because they're all paused at exit). Still pretty hacky, but less hacky than checking the isolate name.

Martin suggested looking for the isolate that has `id == originId`, but I don't see `originId` in the VM service spec so that might be a VM specific solution.

**Comment by aam** [comment]
> Looking at that code link, they're catching the first `EventKind.kIsolateStart` event. But package:coverage usually doesn't subscribe to the event stream early enough to catch that.

Can you launch the app in `pause-isolates-on-start` mode therefore guaranteeing that you get full picture of what is started and in what order?

**Comment by liamappelbe** [comment]
> Can you launch the app in `pause-isolates-on-start` mode therefore guaranteeing that you get full picture of what is started and in what order?

Maybe, but many of our users start the tests themselves, then gather coverage separately. We'd have to convince all of them to change how they invoke the tests.

**Comment by brianquinlan** [comment]
FYI, I just spent a day trying to figure out why some tests were timing out due to this issue. Since the code under test involves native code that uses condition variables, it never occurred to me that this could be an infrastructure problem ;-)
